spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tickety
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12648}
    properties:
      schema: tickety

  flyway:
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12648}
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: ${FLYWAY_MIGRATION_LOCATIONS:classpath:db/migration}
    fail-on-missing-locations: true
    schemas: ${DATABASE_NAME:profile_platform}
    table: flyway_schema_history
    connect-retries: 3
    connect-retries-interval: 60
    repair: false
    ignore-migration-patterns: [ ]
    url: jdbc:postgresql://localhost:5432/tickety


id-info:
  datacenter: 1
  machine-id: 1


server:
  port: 9008
